### PR TITLE
Sensor status

### PR DESCRIPTION
**Pull request by jnewland**
This PR adds support for loading sensor status. My current value, nicely reported via Home Assistant w/ https://github.com/jnewland/home-assistant/commit/c0f615d61477b7de3f15f7188a6041958a969246:

> All doors and windows closed.No motion activity detected.

I'm not sure if `ctl00_phBody_lblSensorStatus` is present on all users' system summary page: is it present on yours? I'd be happy to push up some changes to ensure the absence of this field is gracefully handled, or take other review suggestions. 😄

### CODE REVIEW

**Comment by btotharye** [comment]
It is the same for my sensor on my alarm.com for what its worth:

<span id="ctl00_phBody_lblSensorStatus">Master Bedroom Door is Open.
                        <BR/>No motion activity detected.
                    </span>

**Comment by btotharye** [comment]
its the same on my alarm.com as well:

span id="ctl00_phBody_lblSensorStatus">Master Bedroom Door is Open.

**Comment by btotharye** [comment]
let me know if you want all the info for locks, thermostat, and video I was about to start contributing to this to add those in

**Comment by jnewland** [comment]
> its the same on my alarm.com as well

Thanks for confirming! 🙇 

> let me know if you want all the info for locks, thermostat, and video I was about to start contributing to this to add those in

Yeah feel free to drop 'em here! The data will be helpful no matter what. I don't have any controllable locks or thermostats or anything but I can see how that'd be useful if did and I'm happy to add it to this PR if that ends up being appropriate.

@Xorso gentle ping for your review here. I'd love to make sure I'm on the right path in terms of your desired approach before I start adding more attributes.

**Comment by btotharye** [comment]
Below is the code for locks and thermostat, once I can get a better handle on how to use this library I want to add in my video camera from there as well.  I pinged you in gitter to see how you tested out this library.
[locks_thermostat_code.txt](https://github.com/Xorso/pyalarmdotcom/files/887141/locks_thermostat_code.txt)

**Comment by lorddaren** [comment]
Sorry for the delay I was out of town. 

So it doesn't look like you are handling more than one sensor status. If we had multiple windows or doors open are simply going to report them in one state? I am fine either way. I was trying to simply look for a solution on to configure the sensors and break them up.

**Comment by btotharye** [comment]
It appears from his output and mine it just has them all in that one command there.  I would love to see the thermostat and lock stuff go in as well, let me know if you need anything else on those, figured I'd just give you the code and it would be faster for you to do it than me.

**Comment by jnewland** [comment]
> It appears from his output and mine it just has them all in that one command there.

Yeah it doesn't look like individual sensors are exposed anywhere on the "pda" version site. I wish I could get individual states too :/.

**Comment by shaun040** [comment]
Any update on this getting merged so we can add it to Home Assistant officially?

**Comment by lorddaren** [comment]
I guess we can use templates to parse out the status, but I was trying to find a way to actually get the status of sensors from the full site. I can merge this for now, but will need to some time to push the update to Pypi. I received a new computer and have to get everything set back up again.

**Pull request merged**
